name: Build main

on:
  push:
    branches:
      - main

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'justjavac/v8.js.cn'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
